version: '3.8'

services:
  # MySQL 데이터베이스
  mysql:
    image: mysql:8.0
    container_name: pleasybank-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: pleasybank
      MYSQL_USER: pleasyuser
      MYSQL_PASSWORD: pleasypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pleasybank-network

  # MySQL 관리 도구
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pleasybank-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - pleasybank-network

  # Redis (선택)
  redis:
    image: redis:6.2-alpine
    container_name: pleasybank-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pleasybank-network

  # MinIO (선택)
  minio:
    image: minio/minio
    container_name: pleasybank-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # 웹 콘솔
    volumes:
      - minio_data:/data
    networks:
      - pleasybank-network

networks:
  pleasybank-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
  minio_data: