version: '3.8'

services:
  # MySQL 데이터베이스
  db:
    image: mysql:8.0
    container_name: pleasybank-mysql
    restart: always
    environment:
      MYSQL_DATABASE: pleasybank
      MYSQL_USER: pleasyuser
      MYSQL_PASSWORD: pleasypassword
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # MySQL 관리 도구
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pleasybank-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - pleasybank-network

  # Redis (선택)
  redis:
    image: redis:6.2-alpine
    container_name: pleasybank-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pleasybank-network

  # MinIO (선택)
  minio:
    image: minio/minio
    container_name: pleasybank-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # 웹 콘솔
    volumes:
      - minio_data:/data
    networks:
      - pleasybank-network

networks:
  pleasybank-network:
    driver: bridge

volumes:
  mysql-data:
  redis_data:
  minio_data: