spring:
  datasource:
    url: jdbc:h2:mem:pleasybank
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: dfbb49ef3546d43dae6f375358b0008e
            client-secret: 35MeziawqseZYqTsecXvsLnNWuMhUXjj
            redirect-uri: http://localhost:8080/api/auth/oauth2/callback/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

# 로깅 설정
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /api

# JWT 및 인증 설정
app:
  auth:
    token-secret: ${JWT_SECRET:pleasyBankSecretKey012345678901234567890123456789}
    token-expiration-ms: 3600000  # 1 hour
    refresh-token-expiration-ms: 2592000000  # 30 days
  oauth2:
    authorized-redirect-uris:
      - http://localhost:3000/oauth2/redirect