spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/pleasybank?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: pleasyuser
    password: pleasypassword
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      minimum-idle: 1
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      continue-on-error: true
  session:
    store-type: redis
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID:dfbb49ef3546d43dae6f375358b0008e}
            client-secret: ${KAKAO_CLIENT_SECRET:tCi6WRWfWenBMrfbTaTH502WjYkHOsDI}
            redirect-uri: '{baseUrl}/api/auth/kakao/callback'
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  data:
    redis:
      enabled: true
      host: localhost
      port: 6379
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  # 파일 업로드 설정
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  servlet:
    context-path: /
    compression:
      enabled: true
    
logging:
  level:
    root: INFO
    com.pleasybank: INFO
    com.pleasybank.domain: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    
jwt:
  secret-key: pleasybank123456789pleasybank123456789pleasybank123456789
  access-token-expiration-ms: 864000000
  refresh-token-expiration-ms: 2592000000
    
app:
  auth:
    tokenSecret: ${jwt.secret-key}
    tokenExpirationMsec: ${jwt.access-token-expiration-ms}
    refreshTokenExpirationMsec: ${jwt.refresh-token-expiration-ms}
  oauth2:
    redirect-uri: http://localhost:3000/auth/oauth-callback
    kakao:
      client-id: ${KAKAO_CLIENT_ID:dfbb49ef3546d43dae6f375358b0008e}
      redirect-uri: http://localhost:8080/api/auth/kakao/callback
      response-type: code
  cors:
    allowed-origins: http://localhost:3000
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: Authorization,Content-Type,Accept
    max-age: 3600
    allow-credentials: true
    
# 가상 금융 API 설정
finance:
  api:
    mock-enabled: true
    base-url: /api/mock
    account-endpoint: /accounts
    transfer-endpoint: /transfers
    product-endpoint: /products

# MinIO 설정
minio:
  enabled: true  # MinIO 활성화
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: pleasybank
  defaultBuckets:
    - profiles
    - documents
    - products 